(eval-after-load "term"
  '(define-keys term-raw-map
     ("DEL" 'term-send-backspace)
     ("<tab>" 'term-send-tab)
     ("C-q" 'term-send-quoted)
     ("C-x" nil)
     ("C-z" nil)
     ("M-o" nil)
     ("M-x" nil)
     ("M-:" nil)
     ("M-!" nil)
     ("M-&" nil)
     ("C-v" nil)
     ("M-v" nil)
     ("M->" nil)
     ("M-<" nil)
     ("C-s" nil)
     ("C-r" nil)
     ("C-h" nil)
     ("C-c DEL" nil)
     ))
