(load "webjump")
(load "json")

(defvar taylan-webjumps
  `(("SRFI"
     ("http://srfi.schemers.org/"
      "http://srfi.schemers.org/srfi-" "/"))

    ("gnuml"
     ("https://lists.gnu.org/archive/html/"
      "https://lists.gnu.org/archive/html/" "/"))

    ("Google"
     ("https://www.google.com/"
      "https://www.google.com/search?q=" ""))

    ("StartPage"
     ("https://www.startpage.com/"
      "https://www.startpage.com/do/search?q=" ""))

    ("Image"
     ("https://www.startpage.com/eng/pics"
      "https://www.startpage.com/do/search?cat=pics&q=" ""))

    ("Wikipedia"
     ("https://www.wikipedia.org/"
      "https://en.wikipedia.org/wiki/Special:Search?search=" ""))

    ("Wiktionary"
     ("https://www.wiktionary.org/"
      "https://en.wiktionary.org/wiki/Special:Search?search=" ""))

    ("RomajiDesu"
     ("http://www.romajidesu.com/"
      "http://www.romajidesu.com/dictionary/meaning-of-" ".html"))

    ("Emacs Wiki"
     ("http://www.emacswiki.org/"
      "http://www.emacswiki.org/emacs/" ""))

    ("YouTube"
     ("https://www.youtube.com/"
      "https://www.youtube.com/results?search_query=" ""))

    ("Google Translate"
     ("http://translate.google.com/"
      "http://translate.google.com/#auto/_/" ""))

    ("Urban Dictionary"
     ("http://urbandictionary.com/"
      "http://urbandictionary.com/define.php?term=" ""))

    ("Facebook"
     "https://www.facebook.com/")

    ("Twitter"
     "https://www.twitter.com/")

    ("Reddit"
     "https://www.reddit.com/")

    ("Sparkasse Laubach-Hungen"
     "http://spk-laubach-hungen.de/")

    ("The Pirate Bay"
     ("https://thepiratebay.se/"
      "https://thepiratebay.se/search/" ""))

    ("Torrentz.eu"
     ("https://torrentz2.eu/"
      "https://torrentz2.eu/search?f=" ""))

    ;; Username: tmpuser9001
    ;; Password: tmpuser9002
    ;; E-Mail:   tmpuser9001@safetymail.info
    ("BakaBT"
     ("http://bakabt.me/"
      "http://bakabt.me/browse.php?q=" ""))

    ("nyaa"
     ("http://www.nyaa.si/"
      "http://www.nyaa.si/?f=1&c=1_2&q=" ""))

    ("Hidden Wiki"
     "http://zqktlwi4fecvo6ri.onion/wiki/index.php/Main_Page")

    ("Tor Links"
     "http://torlinkbgs6aabns.onion/")

    ("Onion List"
     "http://jh32yv5zgayyyts3.onion/")

    ("Freenet"
     "http://127.0.0.1:8888/")

    ("I2P"
     "http://127.0.0.1:7657/home")

    ("Unitymedia Router Configuration"
     "http://192.168.0.1/")

    )
  "Webjumps in custom format.  See `webjumps-taylan.el'.")

(let (conkeror-webjumps)
  (cl-loop
   for (name value) in taylan-webjumps
   do (progn
        (aput 'webjump-sites
              name
              (cond ((listp value)
                     (apply 'vector 'simple-query value))
                    (t
                     value)))
        (aput 'conkeror-webjumps
              (replace-regexp-in-string " " "" (downcase name))
              (cond ((listp value)
                     (concat (nth 1 value) "%s" (nth 2 value)))
                    (t
                     value)))))
  (save-excursion
    (find-file (sysfile 'home-config "conkeror" "webjumps-taylan.js"))
    (erase-buffer)
    (insert "// Auto-generated by Emacs.\n")
    (insert (concat "define_webjumps("
                    (json-encode conkeror-webjumps)
                    ");"))
    (insert "provide(\"webjumps-taylan\")")
    (save-buffer)
    (kill-buffer)))

(defun webjump-ido ()
  "Like `webjump', but with IDO."
  (interactive)
  (let* ((item (assoc-string
                (ido-completing-read "WebJump: "
                                     (mapcar #'car webjump-sites))
                webjump-sites t))
         (name (car item))
         (expr (cdr item)))
    (browse-url
     (webjump-url-fix
      (cond ((not expr) "")
            ((stringp expr) expr)
            ((vectorp expr) (webjump-builtin expr name))
            ((listp expr) (eval expr))
            ((symbolp expr)
             (if (fboundp expr)
                 (funcall expr name)
               (error "WebJump URL function \"%s\" undefined"
                      expr)))
            (t (error "WebJump URL expression for \"%s\" invalid"
                      name)))))))
